/** BBS TEKNOLOJİ — Hotspot Gateway Referans Listesi (PDF şablonundan sabit) */

export type ReferenceEntry = { name: string; location: string };
export type ReferenceCategory = {
  title: string;
  colHeader: string; // "Kurum / Referans" veya "Birlik / Kurum"
  entries: ReferenceEntry[];
};

export const REFERENCE_CATEGORIES: ReferenceCategory[] = [
  {
    title: "KAMU KURUMLARI",
    colHeader: "Kurum / Referans",
    entries: [
      { name: "Erzurum Barosu", location: "Erzurum-Merkez" },
      { name: "Eskişehir Şeker Fabrikası A.Ş.", location: "Eskişehir-Merkez" },
      { name: "D.S.İ 12.Bölge Müdürlüğü – Kayseri", location: "Kayseri-Merkez" },
    ],
  },
  {
    title: "BELEDİYELER",
    colHeader: "Kurum / Referans",
    entries: [
      { name: "Gümüşhane Belediyesi", location: "Gümüşhane-Merkez" },
      { name: "İskenderun Belediyesi", location: "Hatay-İskenderun" },
      { name: "İstanbul Arnavutköy Belediyesi", location: "İstanbul-Arnavutköy" },
      { name: "İstanbul Büyükçekmece Belediyesi", location: "İstanbul-Büyükçekmece" },
      { name: "Kırıkkale Belediyesi", location: "Kırıkkale-Merkez" },
      { name: "Tunceli Belediyesi", location: "Tunceli-Merkez" },
    ],
  },
  {
    title: "ÜNİVERSİTELER VE EĞİTİM",
    colHeader: "Kurum / Referans",
    entries: [
      { name: "Onay Öğrenci Yurdu – Erzurum", location: "Erzurum-Merkez" },
      { name: "Kampüs Anadolu Kız Yurdu – Eskişehir", location: "Eskişehir-Merkez" },
      { name: "Şeker Apart – Gümüşhane", location: "Gümüşhane-Merkez" },
      { name: "Sıla Erkek Öğrenci Yurdu – Gümüşhane", location: "Gümüşhane-Merkez" },
      { name: "Kayaşehir Petek Koleji – İstanbul", location: "İstanbul-Başakşehir" },
      { name: "Acıbadem Üniversitesi Öğrenci Yurdu – İstanbul", location: "İstanbul-Merkez" },
      { name: "Acıbadem Üniversitesi – İstanbul", location: "İstanbul-Merkez" },
      { name: "İlim Yayma Cemiyeti Öğrenci Yurtları – İstanbul", location: "İstanbul-Merkez" },
    ],
  },
  {
    title: "OTELLER VE TURİZM",
    colHeader: "Kurum / Referans",
    entries: [
      { name: "True Blue Boutique Hotel – Kaş / Antalya", location: "Antalya-Kaş" },
      { name: "True Blue Payava Hotel – Kaş / Antalya", location: "Antalya-Kaş" },
      { name: "Hotel Club Kuştur ***** – Kuşadası", location: "Aydın-Kuşadası" },
      { name: "Korumar De Luxe Hotel ***** / Kuşadası", location: "Aydın-Kuşadası" },
      { name: "Kuştur Club Holiday Village – Kuşadası / Aydın", location: "Aydın-Kuşadası" },
      { name: "Ejder 3200 World Ski Center Konaklı / Erzurum", location: "Erzurum-Konaklı" },
      { name: "Ramada Hotel – Gümüşhane", location: "Gümüşhane-Merkez" },
      { name: "Yeniçeri Grand Hotel – Gümüşhane", location: "Gümüşhane-Merkez" },
      { name: "Nish Suit Hotels – Ataşehir / İstanbul", location: "İstanbul-Ataşehir" },
      { name: "Nish Suit Hotels – Beşiktaş / İstanbul", location: "İstanbul-Beşiktaş" },
      { name: "Boss Hotel Sultanahmet / İstanbul", location: "İstanbul-Fatih" },
      { name: "Nish Suit Hotels – Ümraniye / İstanbul", location: "İstanbul-Ümraniye" },
      { name: "KoruMar Ephesus Beach & Spa Resort ***** Selçuk / İzmir", location: "İzmir-Selçuk" },
      { name: "Polat Apart / Kırıkkale", location: "Kırıkkale-Merkez" },
      { name: "Kayakapi Premium Caves – Cappadocia", location: "Nevşehir-Merkez" },
      { name: "Dinler Hotel ***** – Ürgüp", location: "Nevşehir-Ürgüp" },
      { name: "Akpolat Suite Deluxe Hotel – Sivas", location: "Sivas-Merkez" },
      { name: "Ramada Hotel – Sivas", location: "Sivas-Merkez" },
    ],
  },
  {
    title: "SANAYİ VE ÖZEL SEKTÖR",
    colHeader: "Kurum / Referans",
    entries: [
      { name: "Kaplan Kardeşler Halı A.Ş / Gaziantep", location: "Gaziantep-Merkez" },
      { name: "Merinos Halı A.Ş. – Gaziantep", location: "Gaziantep-Merkez" },
      { name: "Milat Halı A.Ş. – Gaziantep", location: "Gaziantep-Merkez" },
      { name: "A.Döksan Döküm Sanayi A.Ş / İstanbul", location: "İstanbul-Merkez" },
      { name: "Akzo Nobel Server Boya A.Ş. – İstanbul", location: "İstanbul-Merkez" },
      { name: "DFDS Denizcilik A.Ş. – İstanbul", location: "İstanbul-Merkez" },
      { name: "Dinarsu İmalat A.Ş. – İstanbul", location: "İstanbul-Merkez" },
      { name: "Enerya Enerji A.Ş.", location: "İstanbul-Merkez" },
      { name: "Erdemoğlu Holding – İstanbul", location: "İstanbul-Merkez" },
      { name: "Gürsa Oluklu Mukavva ve Ambalaj – İstanbul", location: "İstanbul-Merkez" },
      { name: "İstanbul Spor A.Ş. (IBB İştiraki)", location: "İstanbul-Merkez" },
      { name: "Rekarma Makine San. ve Tic. A.Ş. – İstanbul", location: "İstanbul-Merkez" },
      { name: "Timon Mega A.Ş.", location: "İstanbul-Merkez" },
      { name: "Dearsan Shipyard – İstanbul", location: "İstanbul-Tuzla" },
      { name: "Queen Tarım A.Ş. – İzmir", location: "İzmir-Merkez" },
      { name: "İskur Tekstil A.Ş. – Kahramanmaraş", location: "Kahramanmaraş-Merkez" },
      { name: "Akal İplik Tekstil A.Ş. / Zonguldak", location: "Zonguldak-Merkez" },
    ],
  },
  {
    title: "HASTANELER VE SAĞLIK",
    colHeader: "Kurum / Referans",
    entries: [
      { name: "Adana Hastanesi", location: "Adana-Merkez" },
      { name: "Adana Ortopedi Hastanesi", location: "Adana-Merkez" },
      { name: "Ankara Hastanesi", location: "Ankara-Merkez" },
      { name: "Birtom Medikal ve Sağlık Hizmetleri / Bartın", location: "Bartın-Merkez" },
      { name: "Gemlik Devlet Hastanesi", location: "Bursa-Gemlik" },
      { name: "Bursa Hastanesi", location: "Bursa-Merkez" },
      { name: "Eskişehir Hastanesi", location: "Eskişehir-Merkez" },
      { name: "Ataşehir Hastanesi", location: "İstanbul-Ataşehir" },
      { name: "Ataşehir Tıp Merkezi", location: "İstanbul-Ataşehir" },
      { name: "Bakırköy Hastanesi", location: "İstanbul-Bakırköy" },
      { name: "Yeşilköy International Hastanesi", location: "İstanbul-Bakırköy" },
      { name: "Etiler Tıp Merkezi", location: "İstanbul-Beşiktaş" },
      { name: "Beylikdüzü Tıp Merkezi", location: "İstanbul-Beylikdüzü" },
      { name: "Taksim Hastanesi", location: "İstanbul-Beyoğlu" },
      { name: "Bağdat Caddesi Tıp Merkezi", location: "İstanbul-Kadıköy" },
      { name: "Kadıköy Hastanesi", location: "İstanbul-Kadıköy" },
      { name: "Kozyatağı Hastanesi", location: "İstanbul-Kadıköy" },
      { name: "Atakent Hastanesi", location: "İstanbul-Küçükçekmece" },
      { name: "Acıbadem Hastaneleri", location: "İstanbul-Merkez" },
      { name: "Acıbademi Bupa Sağlık Sigorta A.Ş. – İstanbul", location: "İstanbul-Merkez" },
      { name: "Genel Müdürlük", location: "İstanbul-Merkez" },
      { name: "Özel Kurtköy Ersoy Hastaneleri – İstanbul", location: "İstanbul-Pendik" },
      { name: "Maslak Hastanesi", location: "İstanbul-Sarıyer" },
      { name: "Acıbadem Fulya Sporcu Sağlığı Merkezi", location: "İstanbul-Şişli" },
      { name: "Fulya Hastanesi", location: "İstanbul-Şişli" },
      { name: "Altunizade Hastanesi", location: "İstanbul-Üsküdar" },
      { name: "İzmir Kent Hastanesi", location: "İzmir-Merkez" },
      { name: "Necip Fazıl Devlet Hastanesi – Kahramanmaraş", location: "Kahramanmaraş-Merkez" },
      { name: "Kayseri Hastanesi", location: "Kayseri-Merkez" },
      { name: "Kocaeli Hastanesi", location: "Kocaeli-Merkez" },
      { name: "Bodrum Hastanesi", location: "Muğla-Bodrum" },
      { name: "Bodrum Tıp Merkezi", location: "Muğla-Bodrum" },
    ],
  },
  {
    title: "ASKERİ REFERANSLAR",
    colHeader: "Birlik / Kurum",
    entries: [
      { name: "Eğitim Doktrin Komutanlığı Askeri Gazino Müdürlüğü", location: "Ankara-Merkez" },
      { name: "Eğitim Doktrin Komutanlığı Kantin Başkanlığı", location: "Ankara-Merkez" },
      { name: "Topçu ve Füze Okulu Komutanlığı Gazino Müdürlüğü", location: "Ankara-Polatlı" },
      { name: "Topçu ve Füze Okulu Komutanlığı Gazino Müdürlüğü", location: "Ankara-Polatlı" },
      { name: "Topçu ve Füze Okulu Komutanlığı Kantin Başkanlığı", location: "Ankara-Polatlı" },
      { name: "Karpuzkaldıran Özel Eğitim Merkez Komutanlığı", location: "Antalya-Merkez" },
      { name: "25. Hudut Tugay Komutan Yardımcılığı Askeri Gazino Müdürlüğü", location: "Artvin-Merkez" },
      { name: "1. Mekanize Piyade Tugay Komutanlığı Kışla Gazino Müdürlüğü", location: "Ağrı-Doğubeyazıt" },
      { name: "Bakım Okulu ve Eğitim Merkez Komutanlığı Kışla Gazino Müdürlüğü", location: "Balıkesir-Merkez" },
      { name: "Balıkesir Ordu Evi", location: "Balıkesir-Merkez" },
      { name: "17. Komando Tugay Komutan Yardımcılığı Gazino Müdürlüğü", location: "Bayburt-Merkez" },
      { name: "58. Piyade Eğitim Alay Komutanlığı Kantin Başkanlığı", location: "Burdur-Merkez" },
      { name: "Askeri Veterinerlik ve Eğitim Merkezi Komutanlığı Gazino Müdürlüğü", location: "Bursa-Gemlik" },
      { name: "Askeri Veterinerlik ve Eğitim Merkezi Komutanlığı Kantin Başkanlığı", location: "Bursa-Gemlik" },
      { name: "16. Mekanize Piyade Tugay Komutanlığı Kantin Başkanlığı", location: "Diyarbakır-Deve geçidi" },
      { name: "7. Kolordu Komutanlığı Kantin Başkanlığı", location: "Diyarbakır-Merkez" },
      { name: "54. Mekanize Piyade Tugay Komutanlığı Kantin Başkanlığı", location: "Edirne-Merkez" },
      { name: "9. Kolordu Erzurum Garnizon Birleşik Kantin Başkanlığı", location: "Erzurum-Merkez" },
      { name: "9. Kolordu Mekanize Piyade Tabur Komutanlığı Askeri Gazino Müdürlüğü", location: "Erzurum-Oltu" },
      { name: "9. Kolordu Mekanize Piyade Tabur Komutanlığı Kantin Başkanlığı", location: "Erzurum-Oltu" },
      { name: "59. Topçu Eğitim Tugay Komutanlığı Kantin Başkanlığı", location: "Erzincan-Merkez" },
      { name: "Hakkâri Dağ ve Komando Tugay Komutanlığı Gazino Müdürlüğü", location: "Hakkâri-Merkez" },
      { name: "Hakkâri Dağ ve Komando Tugay Komutanlığı Gazino Müdürlüğü", location: "Hakkâri-Otluca" },
      { name: "Hakkâri Dağ ve Komando Tugay Komutanlığı Kantin Başkanlığı", location: "Hakkâri-Otluca" },
      { name: "3. Piyade Tümen Komutanlığı Gazino Müdürlüğü", location: "Hakkâri-Yüksekova" },
      { name: "Milli Savunma Üniversitesi Levent Kampüsü", location: "İstanbul Levent" },
      { name: "Çok Uluslu Tatbikat Merkez Komutanlığı", location: "İstanbul Levent" },
      { name: "Milli Savunma Üniversitesi Maltepe Kampüsü", location: "İstanbul Maltepe" },
      { name: "İstihkam Okul ve Eğitim Merkezi Askeri Gazino Müdürlüğü", location: "İzmir-Narlıdere" },
      { name: "İstihkam Okul ve Eğitim Merkezi Askeri Kantin Başkanlığı", location: "İzmir-Narlıdere" },
      { name: "14. Mekanize Tugay Komutanlığı Kantin Başkanlığı", location: "Kars-Merkez" },
      { name: "1. Zırhlı Tugay Komutanlığı Gazino Müdürlüğü", location: "Kırklareli-Babaeski" },
      { name: "65. Mekanize Tugay Komutanlığı Askeri Gazino Müdürlüğü", location: "Kırklareli-Lüleburgaz" },
      { name: "65. Mekanize Tugay Komutanlığı Kantin Başkanlığı", location: "Kırklareli-Lüleburgaz" },
      { name: "55. Mekanize Piyade Tugay Komutanlığı Askeri Gazino Müdürlüğü", location: "Kırklareli-Merkez" },
      { name: "55. Mekanize Piyade Tugay Komutanlığı Kantin Başkanlığı", location: "Kırklareli-Merkez" },
      { name: "1. Komando Eğitim Tugayı Komutanlığı Askeri Gazino Müdürlüğü", location: "Manisa-Merkez" },
      { name: "1. Komando Eğitim Tugayı Komutanlığı Kantin Başkanlığı", location: "Manisa-Merkez" },
      { name: "70. Mekanize Komutanlığı Askeri Gazino Müdürlüğü", location: "Mardin-Merkez" },
      { name: "14'üncü Komando Tugay Komutanlığı Askeri Gazino Müdürlüğü", location: "Mardin-Midyat" },
      { name: "14'üncü Komando Tugay Komutanlığı Askeri Gazino Müdürlüğü", location: "Mardin-Midyat" },
      { name: "6. Motorlu Piyade Tugay Komutanlığı Gazino Müdürlüğü", location: "Şırnak-Akçay" },
      { name: "6. Motorlu Piyade Tugay Komutanlığı Kantin Başkanlığı", location: "Şırnak-Akçay" },
      { name: "8. Hudut Alay Komutanlığı Askeri Gazino Müdürlüğü", location: "Şırnak-Cizre" },
      { name: "172. Zırhlı Tugay Komutanlığı Kışla Gazino Müdürlüğü", location: "Şırnak-Silopi" },
      { name: "5. Piyade Eğitim Tugay Komutanlığı Askeri Gazino Müdürlüğü", location: "Sivas-Merkez" },
      { name: "5. Piyade Eğitim Tugay Komutanlığı Kantin Başkanlığı", location: "Sivas-Merkez" },
      { name: "5. Kolordu Komutanlığı Merkez Askeri Gazino Müdürlüğü", location: "Tekirdağ-Çorlu Orduevi" },
      { name: "48. Piyade Eğitim Alay Komutanlığı Askeri Gazino Müdürlüğü", location: "Tokat-Merkez" },
      { name: "17. Komando Tugay Komutanlığı Kantin Başkanlığı", location: "Trabzon-Merkez" },
      { name: "6. Hudut Tugay Komutanlığı Gazino Müdürlüğü", location: "Van-Merkez" },
      { name: "Jandarma Asayiş Kolordu Oyun Salonu Acarlar Ticaret", location: "Van-Merkez" },
      { name: "6. Hudut Tugayı 2 Hudut Taburu Acarlar Ticaret", location: "Van-Özalp" },
      { name: "66. Mekanize Piyade Tugay Komutanlığı Askeri Gazino Müdürlüğü", location: "Çorlu-Ulaş" },
      { name: "66. Mekanize Piyade Tugay Komutanlığı Askeri Gazino Müdürlüğü", location: "Çorlu-Ulaş-Şube" },
      { name: "5. Hudut Alay Komutanlığı Kantin Başkanlığı", location: "Iğdır-Merkez" },
    ],
  },
];
